create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  city text not null default 'Metropolis',
  manager_name text not null default 'Property Desk',
  manager_phone text not null default '+1 (555) 019-2834',
  manager_email text not null default 'billing@rentpulse.local',
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tenants (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  unit_number text not null,
  full_name text not null,
  email text not null,
  phone text not null,
  rent_amount numeric(10,2) not null default 0,
  due_day_of_month integer not null default 1 check (due_day_of_month between 1 and 31),
  grace_period_days integer not null default 5,
  current_balance numeric(10,2) not null default 0,
  status text not null default 'active' check (status in ('active','grace','overdue','paid')),
  auto_reminders_enabled boolean not null default true,
  reminder_channel text not null default 'both' check (reminder_channel in ('sms','email','both')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  invoice_number text not null unique,
  period_label text not null,
  amount_due numeric(10,2) not null,
  amount_paid numeric(10,2) not null default 0,
  due_date timestamptz not null,
  grace_until_date timestamptz not null,
  status text not null default 'unpaid' check (status in ('unpaid','partially_paid','paid','overdue')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  invoice_id bigint references public.invoices(id) on delete set null,
  amount numeric(10,2) not null,
  payment_method text not null default 'bank_transfer',
  reference_number text,
  balance_after_payment numeric(10,2) not null,
  next_due_date_after_payment timestamptz,
  receipt_message text not null,
  paid_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.reminder_logs (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(id) on delete cascade,
  invoice_id bigint references public.invoices(id) on delete set null,
  trigger_type text not null check (trigger_type in ('approaching','due_today','overdue','payment_receipt','manual','scheduled_heartbeat')),
  channel text not null check (channel in ('sms','email')),
  recipient text not null,
  message_title text not null,
  message_body text not null,
  balance_mentioned numeric(10,2) not null,
  due_date_mentioned timestamptz,
  status text not null default 'sent' check (status in ('queued','sent','delivered','failed')),
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.reminder_settings (
  id bigint generated by default as identity primary key,
  schedule_cron_task_uid text,
  days_before_due_notice integer not null default 3,
  send_on_due_date boolean not null default true,
  overdue_frequency_days integer not null default 2,
  quiet_hours_start text not null default '21:00',
  quiet_hours_end text not null default '08:00',
  auto_dispatch_enabled boolean not null default true,
  sms_template_approaching text not null default 'Rent reminder: your rent is due soon. Balance: {balance}.',
  sms_template_overdue text not null default 'Rent overdue reminder: amount remaining is {balance}.',
  sms_template_receipt text not null default 'Payment received. Your remaining balance is {balance}.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tenants_property_id_idx on public.tenants(property_id);
create index if not exists invoices_tenant_id_idx on public.invoices(tenant_id);
create index if not exists payments_tenant_id_idx on public.payments(tenant_id);
create index if not exists reminder_logs_tenant_id_idx on public.reminder_logs(tenant_id);

insert into storage.buckets (id, name, public)
values ('rentpulse-reports', 'rentpulse-reports', false)
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.properties enable row level security;
alter table public.tenants enable row level security;
alter table public.invoices enable row level security;
alter table public.payments enable row level security;
alter table public.reminder_logs enable row level security;
alter table public.reminder_settings enable row level security;

create policy if not exists "service role full access users" on public.users for all to service_role using (true) with check (true);
create policy if not exists "service role full access properties" on public.properties for all to service_role using (true) with check (true);
create policy if not exists "service role full access tenants" on public.tenants for all to service_role using (true) with check (true);
create policy if not exists "service role full access invoices" on public.invoices for all to service_role using (true) with check (true);
create policy if not exists "service role full access payments" on public.payments for all to service_role using (true) with check (true);
create policy if not exists "service role full access reminder logs" on public.reminder_logs for all to service_role using (true) with check (true);
create policy if not exists "service role full access reminder settings" on public.reminder_settings for all to service_role using (true) with check (true);
