import { Bell, CheckCircle2, Contact, KeyRound, Smartphone, UserCircle } from "lucide-react";
import { LandlordPageShell, PageNav } from "@/components/LandlordPageShell";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export default function Profile() {
  return <LandlordPageShell title="Profile" eyebrow="Landlord account" description="Manage the landlord profile and understand what RentPulse can access on the phone when the native companion is added."><PageNav /><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-[#f4e8d4] text-lg font-bold text-[#9a6b2d]">MV</div><div><h2 className="font-display text-xl font-bold">Marcus Vance</h2><p className="text-sm text-slate-500">Property manager</p></div></div><div className="mt-7 space-y-4"><Info label="Email" value="marcus@rentpulse.example" /><Info label="Phone" value="+254 700 000 000" /><Info label="Portfolio" value="2 properties · 4 tenants" /></div><Button onClick={() => toast.info("Profile editing is ready for the next settings update") } className="mt-7 w-full bg-[#0b645c] hover:bg-[#09564f]">Edit profile</Button></section><section className="space-y-4"><div className="rounded-2xl bg-[#e5f1ee] p-6 ring-1 ring-[#cce5df]"><div className="flex items-center gap-2 text-[#0b645c]"><Smartphone className="h-5 w-5" /><h2 className="font-display text-lg font-bold">Mobile readiness</h2></div><p className="mt-2 text-sm leading-6 text-[#416c67]">RentPulse is installable as a PWA. The future Android companion will need separate permission setup for payment notifications and SMS delivery.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Permission icon={<Bell className="h-4 w-4" />} label="Notifications" status="PWA supported" /><Permission icon={<Contact className="h-4 w-4" />} label="Contacts" status="Optional" /><Permission icon={<KeyRound className="h-4 w-4" />} label="Secure connection" status="Required" /><Permission icon={<Smartphone className="h-4 w-4" />} label="M-PESA messages" status="Android companion" /></div></div><div className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center gap-2"><UserCircle className="h-5 w-5 text-[#0b645c]" /><h2 className="font-display text-lg font-bold">Workspace preferences</h2></div><div className="mt-4 space-y-3"><Info label="Currency display" value="Use the currency configured on each property" /><Info label="Reminder channel" value="SMS and email ready for connection" /><Info label="Data ownership" value="Landlord-controlled tenant ledger" /></div></div></section></div></LandlordPageShell>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="text-right font-semibold text-slate-800">{value}</span></div>; }
function Permission({ icon, label, status }: { icon: React.ReactNode; label: string; status: string }) { return <div className="flex items-center gap-3 rounded-xl bg-white/75 p-3"><span className="text-[#0b645c]">{icon}</span><div className="min-w-0"><div className="text-xs font-bold text-[#245b55]">{label}</div><div className="mt-0.5 flex items-center gap-1 text-[10px] text-[#5f8982]"><CheckCircle2 className="h-3 w-3" />{status}</div></div></div>; }
